spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database_ms?createDatabaseIfNotExist=true
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

