

server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: 0000
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgre
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: identity-provider
  config:
    import: configserver:http://localhost:8081/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
